name: Build Windows
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: graalvm/setup-graalvm@v1
        with: { java-version: '25', distribution: 'graalvm-community', components: 'native-image' }

      - run: mvn clean install -DskipTests=true
      - shell: bash
        run: |
          mkdir -p native-image/src/main/resources
          # Kopierar från target-mappen
          cp native-image/target/*-jlink.zip native-image/src/main/resources/jlink.zip
          cp application.properties native-image/src/main/resources/
          cp hash.txt native-image/src/main/resources/

      - shell: cmdgit add .github/workflows/linux.yml
        run: |
          call vcvarsall.bat x64
          mvn package -pl native-image -am -DskipTests=true
          
      - name: Verify
        run: .\native-image\target\hedgehog.exe --version












          
          
          


          
          


          