name: Build Windows (amd64) Executable

on:
  push:
    branches: [ main, develop ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Install
        run: mvn clean install -DskipTests=true

      - name: Build Native Image
        shell: cmd
        run: |
          call vcvarsall.bat x64
          set PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64
          mvn package -pl native-image -am -DskipTests=true

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hedgehog-windows-output
          path: native-image/target/hedgehog.exe
          retention-days: 5
          
          
          


          
          


          